# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    swa deploy --app-location ./build --deployment-token 9d9bfa526ef5de1035bb256e3b0c365592de2eaeab2ad2ea7e25d0f71462165906-0618a1cb-d161-4cc2-81b8-2a932a76d675010051704ff0f210 --env prod
  displayName: 'npm install and build'
